In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
dataframe = pd.read_csv('Data/Wine.csv')

In [3]:
dataframe.shape

(178, 14)

In [4]:
dataframe.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [5]:
dataframe.describe().transpose()

count        mean         std     min       25%  \
Alcohol               178.0   13.000618    0.811827   11.03   12.3625   
Malic_Acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Ash_Alcanity          178.0   19.494944    3.339564   10.60   17.2000   
Magnesium             178.0   99.741573   14.282484   70.00   88.0000   
Total_Phenols         178.0    2.295112    0.625851    0.98    1.7425   
Flavanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid_Phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanthocyanins       178.0    1.590899    0.572359    0.41    1.2500   
Color_Intensity       178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD280                 178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   
Customer_Segment      178.0    1.938202    0.775035    1.00    1.0000   

                          50%       75%      max  
Alcohol                13.050   13.6775    14.83  
Malic_Acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Ash_Alcanity           19.500   21.5000    30.00  
Magnesium              98.000  107.0000   162.00  
Total_Phenols           2.355    2.8000     3.88  
Flavanoids              2.135    2.8750     5.08  
Nonflavanoid_Phenols    0.340    0.4375     0.66  
Proanthocyanins         1.555    1.9500     3.58  
Color_Intensity         4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD280                   2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00  
Customer_Segment        2.000    3.0000     3.00

In [6]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Alcohol               178 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             178 non-null    int64  
 5   Total_Phenols         178 non-null    float64
 6   Flavanoids            178 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       178 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 178 non-null    float64
 12  Proline               178 non-null    int64  
 13  Customer_Segment      178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [7]:
dataframe.Customer_Segment.value_counts()

2    71
1    59
3    48
Name: Customer_Segment, dtype: int64

In [8]:
val_dataframe = dataframe.sample(frac=0.2, random_state=1337)

In [9]:
val_dataframe

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
44     13.05        1.77  2.10          17.0        107           3.00   
154    12.58        1.29  2.10          20.0        103           1.48   
133    12.70        3.55  2.36          21.5        106           1.70   
34     13.51        1.80  2.65          19.0        110           2.35   
21     12.93        3.80  2.65          18.6        102           2.41   
37     13.05        1.65  2.55          18.0         98           2.45   
70     12.29        1.61  2.21          20.4        103           1.10   
35     13.48        1.81  2.41          20.5        100           2.70   
25     13.05        2.05  3.22          25.0        124           2.63   
13     14.75        1.73  2.39          11.4         91           3.10   
32     13.68        1.83  2.36          17.2        104           2.42   
36     13.28        1.64  2.84          15.5        110           2.60   
96     11.81        2.12  2.74          21.5        134           1.60   
55     13.56        1.73  2.46          20.5        116           2.96   
107    12.72        1.75  2.28          22.5         84           1.38   
43     13.24        3.98  2.29          17.5        103           2.64   
39     14.22        3.99  2.51          13.2        128           3.00   
52     13.82        1.75  2.42          14.0        111           3.88   
106    12.25        1.73  2.12          19.0         80           1.65   
62     13.67        1.25  1.92          18.0         94           2.10   
24     13.50        1.81  2.61          20.0         96           2.53   
1      13.20        1.78  2.14          11.2        100           2.65   
54     13.74        1.67  2.25          16.4        118           2.60   
63     12.37        1.13  2.16          19.0         87           3.50   
19     13.64        3.10  2.56          15.2        116           2.70   
121    11.56        2.05  3.23          28.5        119           3.18   
135    12.60        2.46  2.20          18.5         94           1.62   
66     13.11        1.01  1.70          15.0         78           2.98   
128    12.37        1.63  2.30          24.5         88           2.22   
149    13.08        3.90  2.36          21.5        113           1.41   
120    11.45        2.40  2.42          20.0         96           2.90   
102    12.34        2.45  2.46          21.0         98           2.56   
124    11.87        4.31  2.39          21.0         82           2.86   
132    12.81        2.31  2.40          24.0         98           1.15   
118    12.77        3.43  1.98          16.0         80           1.63   
28     13.87        1.90  2.80          19.4        107           2.95   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity  \
44         3.00                  0.28             2.03             5.04   
154        0.58                  0.53             1.40             7.60   
133        1.20                  0.17             0.84             5.00   
34         2.53                  0.29             1.54             4.20   
21         2.41                  0.25             1.98             4.50   
37         2.43                  0.29             1.44             4.25   
70         1.02                  0.37             1.46             3.05   
35         2.98                  0.26             1.86             5.10   
25         2.68                  0.47             1.92             3.58   
13         3.69                  0.43             2.81             5.40   
32         2.69                  0.42             1.97             3.84   
36         2.68                  0.34             1.36             4.60   
96         0.99                  0.14             1.56             2.50   
55         2.78                  0.20             2.45             6.25   
107        1.76                  0.48             1.63             3.30   
43         2.63                  0.32             1.66            

In [10]:
val_dataframe.index

Int64Index([ 44, 154, 133,  34,  21,  37,  70,  35,  25,  13,  32,  36,  96,
             55, 107,  43,  39,  52, 106,  62,  24,   1,  54,  63,  19, 121,
            135,  66, 128, 149, 120, 102, 124, 132, 118,  28],
           dtype='int64')

In [11]:
train_dataframe = dataframe.drop(val_dataframe.index)

In [12]:
print(
    "Using %d samples for training and %d for validation"
    % (len(train_dataframe), len(val_dataframe))
)

Using 142 samples for training and 36 for validation


In [13]:
# PLOT TWIST #1
from tensorflow.keras.utils import to_categorical

In [14]:
def dataframe_to_dataset(dataframe):
    dataframe = dataframe.copy()
    labels = to_categorical(dataframe.pop("Customer_Segment"))
    ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
    ds = ds.shuffle(buffer_size=len(dataframe))
    return ds

In [15]:
train_ds = dataframe_to_dataset(train_dataframe)
val_ds = dataframe_to_dataset(val_dataframe)

2022-02-16 17:16:28.077159: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [16]:
for x, y in train_ds.take(1):
    print("Input:", x)
    print("Target:", y)

Input: {'Alcohol': <tf.Tensor: shape=(), dtype=float64, numpy=13.56>, 'Malic_Acid': <tf.Tensor: shape=(), dtype=float64, numpy=1.71>, 'Ash': <tf.Tensor: shape=(), dtype=float64, numpy=2.31>, 'Ash_Alcanity': <tf.Tensor: shape=(), dtype=float64, numpy=16.2>, 'Magnesium': <tf.Tensor: shape=(), dtype=int64, numpy=117>, 'Total_Phenols': <tf.Tensor: shape=(), dtype=float64, numpy=3.15>, 'Flavanoids': <tf.Tensor: shape=(), dtype=float64, numpy=3.29>, 'Nonflavanoid_Phenols': <tf.Tensor: shape=(), dtype=float64, numpy=0.34>, 'Proanthocyanins': <tf.Tensor: shape=(), dtype=float64, numpy=2.34>, 'Color_Intensity': <tf.Tensor: shape=(), dtype=float64, numpy=6.13>, 'Hue': <tf.Tensor: shape=(), dtype=float64, numpy=0.95>, 'OD280': <tf.Tensor: shape=(), dtype=float64, numpy=3.38>, 'Proline': <tf.Tensor: shape=(), dtype=int64, numpy=795>}
Target: tf.Tensor([0. 1. 0. 0.], shape=(4,), dtype=float32)


In [17]:
# Q: Why use batch?
# A: 
train_ds = train_ds.batch(5)
val_ds = val_ds.batch(5)

In [18]:
from tensorflow.keras.layers import Normalization

In [19]:
def encode_numerical_feature(feature, name, dataset):
    # Create a Normalization layer for our feature
    normalizer = Normalization()

    # Prepare a Dataset that only yields our feature
    feature_ds = dataset.map(lambda x, y: x[name])
    feature_ds = feature_ds.map(lambda x: tf.expand_dims(x, -1))

    # Learn the statistics of the data
    normalizer.adapt(feature_ds)

    # Normalize the input feature
    encoded_feature = normalizer(feature)
    return encoded_feature


In [20]:
alcohol= keras.Input(shape=(1,), name="Alcohol")
malic_acid= keras.Input(shape=(1,), name="Malic_Acid")
ash= keras.Input(shape=(1,), name="Ash")
ash_alcanity= keras.Input(shape=(1,), name="Ash_Alcanity")
magnesium= keras.Input(shape=(1,), name="Magnesium")
total_phenols= keras.Input(shape=(1,), name="Total_Phenols")
flavanoids= keras.Input(shape=(1,), name="Flavanoids")
nonflavanoid_phenols= keras.Input(shape=(1,), name="Nonflavanoid_Phenols")
proanthocyanins= keras.Input(shape=(1,), name="Proanthocyanins")
color_intensity= keras.Input(shape=(1,), name="Color_Intensity")
hue= keras.Input(shape=(1,), name="Hue")
od280= keras.Input(shape=(1,), name="OD280")
proline= keras.Input(shape=(1,), name="Proline")

In [21]:
all_inputs = [
    alcohol,
    malic_acid,
    ash,
    ash_alcanity,
    magnesium,
    total_phenols,
    flavanoids,
    nonflavanoid_phenols,
    proanthocyanins,
    color_intensity,
    hue,
    od280,
    proline,
]

In [22]:
# Numerical features
alcohol= encode_numerical_feature(alcohol, "Alcohol", train_ds)
malic_acid= encode_numerical_feature(malic_acid, "Malic_Acid", train_ds)
ash= encode_numerical_feature(ash, "Ash", train_ds)
ash_alcanity= encode_numerical_feature(ash_alcanity, "Ash_Alcanity", train_ds)
magnesium= encode_numerical_feature(magnesium, "Magnesium", train_ds)
total_phenols= encode_numerical_feature(total_phenols, "Total_Phenols", train_ds)
flavanoids= encode_numerical_feature(flavanoids, "Flavanoids", train_ds)
nonflavanoid_phenols= encode_numerical_feature(nonflavanoid_phenols, "Nonflavanoid_Phenols", train_ds)
proanthocyanins= encode_numerical_feature(proanthocyanins, "Proanthocyanins", train_ds)
color_intensity= encode_numerical_feature(color_intensity, "Color_Intensity", train_ds)
hue= encode_numerical_feature(hue, "Hue", train_ds)
od280= encode_numerical_feature(od280, "OD280", train_ds)
proline= encode_numerical_feature(proline, "Proline", train_ds)

In [23]:
all_features = layers.concatenate(
    [
        alcohol,
        malic_acid,
        ash,
        ash_alcanity,
        magnesium,
        total_phenols,
        flavanoids,
        nonflavanoid_phenols,
        proanthocyanins,
        color_intensity,
        hue,
        od280,
        proline,
    ]
)

In [24]:
x = layers.Dense(32, activation="relu")(all_features)
x = layers.Dropout(0.5)(x)
# PLOT TWIST #2
output = layers.Dense(4, activation="softmax")(x)
model = keras.Model(all_inputs, output)

# PLOT TWIST #3
model.compile("adam", "categorical_crossentropy", metrics=["accuracy"])

In [25]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 Alcohol (InputLayer)           [(None, 1)]          0           []                               
                                                                                                  
 Malic_Acid (InputLayer)        [(None, 1)]          0           []                               
                                                                                                  
 Ash (InputLayer)               [(None, 1)]          0           []                               
                                                                                                  
 Ash_Alcanity (InputLayer)      [(None, 1)]          0           []                               
                                                                                              

                                                                                                  
 dropout (Dropout)              (None, 32)           0           ['dense[0][0]']                  
                                                                                                  
 dense_1 (Dense)                (None, 4)            132         ['dropout[0][0]']                
                                                                                                  
Total params: 619
Trainable params: 580
Non-trainable params: 39
__________________________________________________________________________________________________


__NOTE about Dropout layer:__  
The Dropout layer randomly sets input units to 0 with a frequency of rate at each step during training time, which helps prevent overfitting

__Results without Dropout layer:__
Epoch 100/100  
29/29 [==============================] - 0s 2ms/step - loss: 0.0020 - accuracy: 1.0000 - val_loss: 0.0577 - val_accuracy: 0.9722


__Results with Dropout layer:__  
Epoch 100/100  
29/29 [==============================] - 0s 2ms/step - loss: 0.0106 - accuracy: 1.0000 - val_loss: 0.0275 - val_accuracy: 1.0000

In [26]:
keras.utils.plot_model(model, show_shapes=True, rankdir="LR")

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model/model_to_dot to work.


In [27]:
model.fit(train_ds, epochs=100, validation_data=val_ds)

Epoch 1/100
29/29 [==============================] - 1s 10ms/step - loss: 1.5368 - accuracy: 0.3099 - val_loss: 1.3476 - val_accuracy: 0.3056
Epoch 2/100
29/29 [==============================] - 0s 2ms/step - loss: 1.2393 - accuracy: 0.4437 - val_loss: 1.1107 - val_accuracy: 0.5833
Epoch 3/100
29/29 [==============================] - 0s 3ms/step - loss: 1.0086 - accuracy: 0.5634 - val_loss: 0.9279 - val_accuracy: 0.7222
Epoch 4/100
29/29 [==============================] - 0s 2ms/step - loss: 0.8065 - accuracy: 0.6831 - val_loss: 0.7912 - val_accuracy: 0.8333
Epoch 5/100
29/29 [==============================] - 0s 3ms/step - loss: 0.6842 - accuracy: 0.7817 - val_loss: 0.6846 - val_accuracy: 0.8611
Epoch 6/100
29/29 [==============================] - 0s 3ms/step - loss: 0.5831 - accuracy: 0.8169 - val_loss: 0.5994 - val_accuracy: 0.8889
Epoch 7/100
29/29 [==============================] - 0s 3ms/step - loss: 0.5492 - accuracy: 0.8521 - val_loss: 0.5218 - val_accuracy: 0.8889
Epoch 8/100


Epoch 59/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0386 - accuracy: 0.9859 - val_loss: 0.0742 - val_accuracy: 0.9722
Epoch 60/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0269 - accuracy: 1.0000 - val_loss: 0.0733 - val_accuracy: 0.9722
Epoch 61/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0256 - accuracy: 1.0000 - val_loss: 0.0703 - val_accuracy: 0.9722
Epoch 62/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0397 - accuracy: 0.9930 - val_loss: 0.0712 - val_accuracy: 0.9722
Epoch 63/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0409 - accuracy: 0.9930 - val_loss: 0.0729 - val_accuracy: 0.9722
Epoch 64/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0579 - accuracy: 0.9930 - val_loss: 0.0716 - val_accuracy: 0.9722
Epoch 65/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0462 - accuracy: 0.9859 - val_loss: 0.0638 - val_accuracy: 0.9722
Epoch 

In [28]:
# Sample with your own
test = dataframe.head(-1)
test

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
172    14.16        2.51  2.48          20.0         91           1.68   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
172        0.70                  0.44             1.24             9.70  0.62   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
172   1.71      660                 3  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  

[177 rows x 14 columns]

In [29]:
# shortcut to convert dataframe to dict
test.drop('Customer_Segment',axis=1,inplace=True)
sample = test.to_dict('r')[0]

/Users/setel/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/var/folders/ks/l2fhkrzd6f1fd06j0ptvfv600000gn/T/ipykernel_2715/818961304.py:3: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  sample = test.to_dict('r')[0]


In [30]:
sample

{'Alcohol': 14.23,
 'Malic_Acid': 1.71,
 'Ash': 2.43,
 'Ash_Alcanity': 15.6,
 'Magnesium': 127,
 'Total_Phenols': 2.8,
 'Flavanoids': 3.06,
 'Nonflavanoid_Phenols': 0.28,
 'Proanthocyanins': 2.29,
 'Color_Intensity': 5.64,
 'Hue': 1.04,
 'OD280': 3.92,
 'Proline': 1065}

In [31]:
input_dict = {name: tf.convert_to_tensor([value]) for name, value in sample.items()}

In [32]:
input_dict

{'Alcohol': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([14.23], dtype=float32)>,
 'Malic_Acid': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.71], dtype=float32)>,
 'Ash': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.43], dtype=float32)>,
 'Ash_Alcanity': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([15.6], dtype=float32)>,
 'Magnesium': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([127], dtype=int32)>,
 'Total_Phenols': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.8], dtype=float32)>,
 'Flavanoids': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.06], dtype=float32)>,
 'Nonflavanoid_Phenols': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.28], dtype=float32)>,
 'Proanthocyanins': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.29], dtype=float32)>,
 'Color_Intensity': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([5.64], dtype=float32)>,
 'Hue': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.04], dtype=float32)

In [33]:
predictions = model.predict(input_dict)

In [34]:
predictions

array([[9.3858284e-07, 9.9999726e-01, 1.6531454e-06, 1.4392015e-07]],
      dtype=float32)

In [35]:
 np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [36]:
for res in predictions:
    print(res)

[0.000 1.000 0.000 0.000]
